import { Meta } from '@/layouts/Meta';
import { Main } from '@/templates/Main';
import { getBackgroundImage } from '@/utils/backgroundImage';
import React from 'react';
import { useAuth } from 'react-oidc-context';
import { getLogin, getUserId } from '@/utils/Helpers';
import { useDeleteUserDataDelete } from '@/api/autoGenerated/user/user';
import { useRouter } from 'next/router';

const Delete = () => {
  const auth = useAuth();
  const router = useRouter();
  const login = getLogin();
  const userDataDelete = useDeleteUserDataDelete();
  let userId = '';
  if (auth.isAuthenticated) {
    userId = getUserId(auth);
  }

  console.log('user.data', userId);

  return (
    <Main
      meta={
        <Meta
          title="Donate Water Surveys"
          description="Review Surveys from Donate water project"
        />
      }
    >
      <div className="relative isolate h-auto bg-black/40 pb-4 ">
        {getBackgroundImage()}
        <div className="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56 ">
          <div className="bg-black/20 p-2 pb-8 text-center backdrop-blur-sm">
            <h1 className="text-4xl font-bold tracking-tight text-white sm:text-6xl">
              Donate Water
            </h1>
            <p className="mt-6 text-lg leading-8 text-gray-300">
              Clicking below delete button will delete the user account and you
              will no longer be able to login to your account.
            </p>
            <p className="mt-6 text-lg leading-8 text-gray-300">
              All the submitted surveys and images will be delete from the
              database.
            </p>
            {!auth.isAuthenticated && (
              <div>
                <p className="mt-6 text-lg leading-8 text-gray-300">
                  Please login to delete your account!
                </p>
                <button
                  type="button"
                  onClick={() => {
                    login();
                  }}
                  className="text-lg font-semibold leading-6 text-white hover:text-gray-400 hover:underline"
                >
                  Login <span aria-hidden="true">→</span>
                </button>
              </div>
            )}
            {auth.isAuthenticated && (
              <div className="mt-10 flex items-center justify-center gap-x-6">
                <button
                  type="button"
                  onClick={() => {
                    if (auth.isAuthenticated) {
                      userDataDelete
                        .mutateAsync({ params: { userId } })
                        .then(() => {
                          auth
                            .signoutSilent()
                            .then()
                            .catch(() => {
                              console.log('logout error');
                            });
                          router.push('/').then();
                        });
                    }
                  }}
                  className="rounded-md bg-red-900 px-3.5 py-2.5 text-lg font-semibold text-gray-500 shadow-sm hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
                >
                  Delete Account
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </Main>
  );
};

export default Delete;
