import { useRouter } from 'next/router';
import React, { useEffect } from 'react';
import { useAuth } from 'react-oidc-context';

import {
  useGetLeaderboard,
  useGetLeaderboardCsv,
} from '@/api/autoGenerated/data/data';
import { Meta } from '@/layouts/Meta';
import { Main } from '@/templates/Main';
import { getBackgroundImage } from '@/utils/backgroundImage';
import { isReviewer } from '@/utils/Helpers';

function LeaderBoard() {
  const router = useRouter();
  const auth = useAuth();
  const { data, isLoading } = useGetLeaderboard({
    MaxResultCount: 1000,
    SkipCount: 0,
  });

  const downloadCsv = useGetLeaderboardCsv(
    { SkipCount: 0, MaxResultCount: 10000 },
    {
      query: { enabled: false },
      request: { headers: { responseType: 'blob' } },
    }
  );

  useEffect(() => {
    if (!auth.isAuthenticated) {
      auth
        .signinSilent()
        .then((user) => {
          if (user === null) {
            router.push('\\').then();
          }
        })
        .catch(() => {
          router.push('\\').then();
        });
    } else if (!isReviewer(auth)) {
      router.push(`${router.basePath}/user`).then();
    }
  }, []);

  // @ts-ignore
  return (
    <Main
      meta={
        <Meta
          title="Donate Water Surveys"
          description="Review Surveys from Donate water project"
        />
      }
    >
      <div className="relative isolate h-screen">
        {getBackgroundImage()}
        <div className="h-auto bg-white/10 pt-32 backdrop-blur-sm">
          <div className="px-4 text-right text-gray-900 hover:text-blue-400">
            <button
              type="submit"
              onClick={() => {
                downloadCsv.refetch().then((res) => {
                  const blob = new Blob([res.data as string], {
                    type: 'text/csv;charset=utf-8;',
                  });
                  const link = document.createElement('a');
                  link.href = URL.createObjectURL(blob);
                  link.setAttribute('download', 'leaderboard.csv');
                  document.body.appendChild(link);
                  link.click();
                  link.remove();
                });
              }}
            >
              Download CSV
            </button>
          </div>
          <div className="bg-black/30 backdrop-blur-sm">
            <div className=" mb-6 flex flex-col sm:px-1 lg:px-12">
              <div className=" -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div className="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
                  <div className="overflow-hidden shadow md:rounded-lg">
                    <table className="min-w-full divide-y divide-gray-300">
                      <thead className="bg-gray-900 text-white">
                        <tr>
                          <th
                            scope="col"
                            className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-white sm:pl-6"
                          >
                            Rank
                          </th>

                          <th
                            scope="col"
                            className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-white sm:pl-6"
                          >
                            User Name
                          </th>
                          <th
                            scope="col"
                            className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-white sm:pl-6"
                          >
                            User Email
                          </th>
                          <th
                            scope="col"
                            className="px-3 py-3.5 text-left text-sm font-semibold text-white"
                          >
                            Survey Count
                          </th>
                          <th
                            scope="col"
                            className="px-3 py-3.5 text-left text-sm font-semibold text-white"
                          >
                            Accepted Surveys/ Tokens Earned
                          </th>
                          <th
                            scope="col"
                            className="px-3 py-3.5 text-left text-sm font-semibold text-white"
                          >
                            Rejected Surveys
                          </th>
                          <th
                            scope="col"
                            className="px-3 py-3.5 text-left text-sm font-semibold text-white"
                          >
                            Image Count
                          </th>
                          <th
                            scope="col"
                            className="px-3 py-3.5 text-left text-sm font-semibold text-white"
                          >
                            Score
                          </th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-200 bg-gray-900 text-white">
                        {!isLoading &&
                          data !== undefined &&
                          data?.map((item: any) => (
                            <tr key={item.userId}>
                              <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
                                {item.rank}
                              </td>
                              <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
                                {item.userName}
                              </td>
                              <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
                                {item.userEmail}
                              </td>
                              <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
                                {item.surveyCount}
                              </td>
                              <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
                                {item.acceptedSurveyCount}
                              </td>
                              <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
                                {item.rejectedSurveyCount}
                              </td>
                              <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
                                {item.totalImagesUploadedCount}
                              </td>
                              <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
                                {item.score}
                              </td>
                            </tr>
                          ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Main>
  );
}

export default LeaderBoard;
