import React from 'react';

import { useGetLeaderboardStats } from '@/api/autoGenerated/leaderboard/leaderboard';
import { getBackgroundImage } from '@/utils/backgroundImage';
import { getLogin } from '@/utils/Helpers';

export default function Landing() {
  const login = getLogin();
  const statsService = useGetLeaderboardStats();

  return (
    <div className="relative isolate h-auto bg-black/40 pb-4 ">
      {getBackgroundImage()}
      <div className="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56 ">
        <div className="bg-black/20 p-2 pb-8 text-center backdrop-blur-sm">
          <h1 className="text-4xl font-bold tracking-tight text-white sm:text-6xl">
            Donate Water
          </h1>
          <p className="mt-6 text-lg leading-8 text-gray-300">
            Review the surveys submitted by mobile app here.
          </p>
          <div className="mt-10 flex items-center justify-center gap-x-6">
            <a
              href="https://play.google.com/store/apps/details?id=com.iiasa.donatewater"
              className="rounded-md bg-black px-3.5 py-2.5 text-lg font-semibold text-gray-500 shadow-sm hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
            >
              Download Apk
            </a>
            <button
              type="button"
              onClick={() => {
                login();
              }}
              className="text-lg font-semibold leading-6 text-white hover:text-gray-400 hover:underline"
            >
              Review Surveys <span aria-hidden="true">→</span>
            </button>
          </div>
        </div>
        <div className="mx-auto grid h-auto max-w-2xl grid-cols-1 gap-px bg-black/5 text-center sm:grid-cols-1 lg:grid-cols-3">
          <div key="stats1" className="px-4 py-2  sm:px-6 lg:px-8">
            <p className="text-lg font-bold leading-6 text-gray-400">Surveys</p>
            <p className=" items-center gap-x-2">
              <span className="text-4xl font-semibold tracking-tight text-white">
                {statsService.data?.surveyCount}
              </span>
            </p>
          </div>
          <div key="stats2" className="px-4 py-2  sm:px-6 lg:px-8">
            <p className="text-lg font-bold leading-6 text-gray-400">Images</p>
            <p className=" items-center gap-x-2">
              <span className="text-4xl font-semibold tracking-tight text-white">
                {statsService.data?.imageCount}
              </span>
            </p>
          </div>
          <div key="stats3" className="px-4 py-2 sm:px-6 lg:px-8">
            <p className="text-lg font-bold leading-6 text-gray-400">
              Reviewed
            </p>
            <p className=" items-center gap-x-2">
              <span className="text-4xl font-semibold tracking-tight text-white">
                {statsService.data?.reviewCount}
              </span>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
