/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { IIASAFieldSurveyEnumReviewStatus } from './iIASAFieldSurveyEnumReviewStatus';

export type GetSurveySurveyIdReviewNextParams = {
reviewStatus?: IIASAFieldSurveyEnumReviewStatus;
next?: boolean;
};
