/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export interface IIASAFieldSurveyDtosUserScore {
  acceptedSurveyCount?: number;
  rank?: number;
  rejectedSurveyCount?: number;
  score?: number;
  surveyCount?: number;
  totalImagesUploadedCount?: number;
  userEmail?: string | null;
  userId?: string;
  userName?: string | null;
}
