/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export interface IIASAFieldSurveyDtosMetaItemDto {
  id?: number;
  index?: number;
  indexValue?: string | null;
  key?: string | null;
}
