/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { IIASAFieldSurveyDtosSurveyMapDtoData } from './iIASAFieldSurveyDtosSurveyMapDtoData';
import type { IIASAFieldSurveyDtosImageDto } from './iIASAFieldSurveyDtosImageDto';
import type { IIASAFieldSurveyDtosCoordinate } from './iIASAFieldSurveyDtosCoordinate';
import type { IIASAFieldSurveyEnumReviewStatus } from './iIASAFieldSurveyEnumReviewStatus';

export interface IIASAFieldSurveyDtosSurveyMapDto {
  creationTime?: string;
  data?: IIASAFieldSurveyDtosSurveyMapDtoData;
  id?: number;
  images?: IIASAFieldSurveyDtosImageDto[] | null;
  location?: IIASAFieldSurveyDtosCoordinate[] | null;
  status?: IIASAFieldSurveyEnumReviewStatus;
}
