/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { IIASAFieldSurveyDtosImageDto } from './iIASAFieldSurveyDtosImageDto';
import type { IIASAFieldSurveyDtosCoordinate } from './iIASAFieldSurveyDtosCoordinate';
import type { IIASAFieldSurveyEnumReviewStatus } from './iIASAFieldSurveyEnumReviewStatus';
import type { IIASAFieldSurveyDtosSurveyQnA } from './iIASAFieldSurveyDtosSurveyQnA';

export interface IIASAFieldSurveyDtosReviewDetailsDto {
  comment?: string | null;
  createOrUpdateTime?: string;
  id?: number;
  images?: IIASAFieldSurveyDtosImageDto[] | null;
  lastUpdatedBy?: string | null;
  lastUpdatedByEmailId?: string | null;
  lastUpdatedById?: string | null;
  location?: IIASAFieldSurveyDtosCoordinate[] | null;
  score?: number;
  status?: IIASAFieldSurveyEnumReviewStatus;
  surveyCreationTime?: string;
  surveyCreator?: string | null;
  surveyCreatorEmailId?: string | null;
  surveyCreatorId?: string | null;
  surveyId?: number;
  surveyQandAs?: IIASAFieldSurveyDtosSurveyQnA[] | null;
  surveyRating?: number;
}
