/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export interface IIASAFieldSurveyDtosQuestionDto {
  id?: number;
  key?: string | null;
  order?: number;
  question?: string | null;
  type?: string | null;
}
