/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { IIASAFieldSurveyDtosCoordinate } from './iIASAFieldSurveyDtosCoordinate';
import type { IIASAFieldSurveyEnumReviewStatus } from './iIASAFieldSurveyEnumReviewStatus';

export interface IIASAFieldSurveyDtosSurveyDto {
  data?: string | null;
  id?: number;
  location?: IIASAFieldSurveyDtosCoordinate[] | null;
  status?: IIASAFieldSurveyEnumReviewStatus;
}
