/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export type IIASAFieldSurveyEnumReviewStatus = typeof IIASAFieldSurveyEnumReviewStatus[keyof typeof IIASAFieldSurveyEnumReviewStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IIASAFieldSurveyEnumReviewStatus = {
  NotReviewed: 'NotReviewed',
  Completed: 'Completed',
  Rejected: 'Rejected',
  Skipped: 'Skipped',
} as const;
