/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export interface IIASAFieldSurveyDtosSurveyQnA {
  answer?: string | null;
  key?: string | null;
  langCode?: string | null;
  order?: number;
  otherAnswer?: string | null;
  question?: string | null;
  type?: string | null;
}
