/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingTypeApiDescriptionModelEnumValuesItem } from './voloAbpHttpModelingTypeApiDescriptionModelEnumValuesItem';
import type { VoloAbpHttpModelingPropertyApiDescriptionModel } from './voloAbpHttpModelingPropertyApiDescriptionModel';

export interface VoloAbpHttpModelingTypeApiDescriptionModel {
  baseType?: string | null;
  enumNames?: string[] | null;
  enumValues?: VoloAbpHttpModelingTypeApiDescriptionModelEnumValuesItem[] | null;
  genericArguments?: string[] | null;
  isEnum?: boolean;
  properties?: VoloAbpHttpModelingPropertyApiDescriptionModel[] | null;
}
