/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementPermissionGroupDto } from './voloAbpPermissionManagementPermissionGroupDto';

export interface VoloAbpPermissionManagementGetPermissionListResultDto {
  entityDisplayName?: string | null;
  groups?: VoloAbpPermissionManagementPermissionGroupDto[] | null;
}
