/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAccountWebAreasAccountControllersModelsLoginResultType } from './voloAbpAccountWebAreasAccountControllersModelsLoginResultType';

export interface VoloAbpAccountWebAreasAccountControllersModelsAbpLoginResult {
  readonly description?: string | null;
  result?: VoloAbpAccountWebAreasAccountControllersModelsLoginResultType;
}
