/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementPermissionGrantInfoDto } from './voloAbpPermissionManagementPermissionGrantInfoDto';

export interface VoloAbpPermissionManagementPermissionGroupDto {
  displayName?: string | null;
  displayNameKey?: string | null;
  displayNameResource?: string | null;
  name?: string | null;
  permissions?: VoloAbpPermissionManagementPermissionGrantInfoDto[] | null;
}
