/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingParameterApiDescriptionModel } from './voloAbpHttpModelingParameterApiDescriptionModel';
import type { VoloAbpHttpModelingMethodParameterApiDescriptionModel } from './voloAbpHttpModelingMethodParameterApiDescriptionModel';
import type { VoloAbpHttpModelingReturnValueApiDescriptionModel } from './voloAbpHttpModelingReturnValueApiDescriptionModel';

export interface VoloAbpHttpModelingActionApiDescriptionModel {
  allowAnonymous?: boolean | null;
  httpMethod?: string | null;
  implementFrom?: string | null;
  name?: string | null;
  parameters?: VoloAbpHttpModelingParameterApiDescriptionModel[] | null;
  parametersOnMethod?: VoloAbpHttpModelingMethodParameterApiDescriptionModel[] | null;
  returnValue?: VoloAbpHttpModelingReturnValueApiDescriptionModel;
  supportedVersions?: string[] | null;
  uniqueName?: string | null;
  url?: string | null;
}
