/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpIdentityIdentityRoleCreateDtoExtraProperties } from './voloAbpIdentityIdentityRoleCreateDtoExtraProperties';

export interface VoloAbpIdentityIdentityRoleCreateDto {
  readonly extraProperties?: VoloAbpIdentityIdentityRoleCreateDtoExtraProperties;
  isDefault?: boolean;
  isPublic?: boolean;
  name: string;
}
