/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpNameValue } from './voloAbpNameValue';

export type VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoLanguagesMap = {[key: string]: VoloAbpNameValue[] | null} | null;
