/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyDto';

export type VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoProperties = {[key: string]: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyDto} | null;
