/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementUpdatePermissionDto } from './voloAbpPermissionManagementUpdatePermissionDto';

export interface VoloAbpPermissionManagementUpdatePermissionsDto {
  permissions?: VoloAbpPermissionManagementUpdatePermissionDto[] | null;
}
