/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingControllerApiDescriptionModel } from './voloAbpHttpModelingControllerApiDescriptionModel';

export type VoloAbpHttpModelingModuleApiDescriptionModelControllers = {[key: string]: VoloAbpHttpModelingControllerApiDescriptionModel} | null;
