/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpUsersUserData } from './voloAbpUsersUserData';

export interface VoloAbpApplicationDtosListResultDto1VoloAbpUsersUserDataVoloAbpUsersAbstractionsVersion7020CultureNeutralPublicKeyTokenNull {
  items?: VoloAbpUsersUserData[] | null;
}
