/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpIdentityIdentityRoleUpdateDtoExtraProperties } from './voloAbpIdentityIdentityRoleUpdateDtoExtraProperties';

export interface VoloAbpIdentityIdentityRoleUpdateDto {
  concurrencyStamp?: string | null;
  readonly extraProperties?: VoloAbpIdentityIdentityRoleUpdateDtoExtraProperties;
  isDefault?: boolean;
  isPublic?: boolean;
  name: string;
}
