/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpValidationStringValuesIStringValueTypeProperties } from './voloAbpValidationStringValuesIStringValueTypeProperties';
import type { VoloAbpValidationStringValuesIValueValidator } from './voloAbpValidationStringValuesIValueValidator';

export interface VoloAbpValidationStringValuesIStringValueType {
  readonly name?: string | null;
  readonly properties?: VoloAbpValidationStringValuesIStringValueTypeProperties;
  validator?: VoloAbpValidationStringValuesIValueValidator;
}
