/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto';

export type VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoResources = {[key: string]: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto} | null;
