/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpIdentityIdentityUserCreateDtoExtraProperties } from './voloAbpIdentityIdentityUserCreateDtoExtraProperties';

export interface VoloAbpIdentityIdentityUserCreateDto {
  email: string;
  readonly extraProperties?: VoloAbpIdentityIdentityUserCreateDtoExtraProperties;
  isActive?: boolean;
  lockoutEnabled?: boolean;
  name?: string | null;
  password: string;
  phoneNumber?: string | null;
  roleNames?: string[] | null;
  surname?: string | null;
  userName: string;
}
