/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto {
  cultureName?: string | null;
  dateTimeFormat?: VoloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto;
  displayName?: string | null;
  englishName?: string | null;
  isRightToLeft?: boolean;
  name?: string | null;
  nativeName?: string | null;
  threeLetterIsoLanguageName?: string | null;
  twoLetterIsoLanguageName?: string | null;
}
