/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpTenantManagementTenantDtoExtraProperties } from './voloAbpTenantManagementTenantDtoExtraProperties';

export interface VoloAbpTenantManagementTenantDto {
  concurrencyStamp?: string | null;
  readonly extraProperties?: VoloAbpTenantManagementTenantDtoExtraProperties;
  id?: string;
  name?: string | null;
}
