/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpTenantManagementTenantCreateDtoExtraProperties } from './voloAbpTenantManagementTenantCreateDtoExtraProperties';

export interface VoloAbpTenantManagementTenantCreateDto {
  adminEmailAddress: string;
  adminPassword: string;
  readonly extraProperties?: VoloAbpTenantManagementTenantCreateDtoExtraProperties;
  name: string;
}
