/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingParameterApiDescriptionModelDefaultValue } from './voloAbpHttpModelingParameterApiDescriptionModelDefaultValue';

export interface VoloAbpHttpModelingParameterApiDescriptionModel {
  bindingSourceId?: string | null;
  constraintTypes?: string[] | null;
  defaultValue?: VoloAbpHttpModelingParameterApiDescriptionModelDefaultValue;
  descriptorName?: string | null;
  isOptional?: boolean;
  jsonName?: string | null;
  name?: string | null;
  nameOnMethod?: string | null;
  type?: string | null;
  typeSimple?: string | null;
}
