/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingModuleApiDescriptionModelControllers } from './voloAbpHttpModelingModuleApiDescriptionModelControllers';

export interface VoloAbpHttpModelingModuleApiDescriptionModel {
  controllers?: VoloAbpHttpModelingModuleApiDescriptionModelControllers;
  remoteServiceName?: string | null;
  rootPath?: string | null;
}
