/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpIdentityIdentityUserUpdateDtoExtraProperties } from './voloAbpIdentityIdentityUserUpdateDtoExtraProperties';

export interface VoloAbpIdentityIdentityUserUpdateDto {
  concurrencyStamp?: string | null;
  email: string;
  readonly extraProperties?: VoloAbpIdentityIdentityUserUpdateDtoExtraProperties;
  isActive?: boolean;
  lockoutEnabled?: boolean;
  name?: string | null;
  password?: string | null;
  phoneNumber?: string | null;
  roleNames?: string[] | null;
  surname?: string | null;
  userName: string;
}
