/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { IIASAFieldSurveyDtosSurveyMapDto } from './iIASAFieldSurveyDtosSurveyMapDto';

export interface VoloAbpApplicationDtosPagedResultDto1IIASAFieldSurveyDtosSurveyMapDtoIIASAFieldSurveyApplicationContractsVersion1000CultureNeutralPublicKeyTokenNull {
  items?: IIASAFieldSurveyDtosSurveyMapDto[] | null;
  totalCount?: number;
}
