/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export interface VoloAbpUsersUserData {
  email?: string | null;
  emailConfirmed?: boolean;
  id?: string;
  isActive?: boolean;
  name?: string | null;
  phoneNumber?: string | null;
  phoneNumberConfirmed?: boolean;
  surname?: string | null;
  tenantId?: string | null;
  userName?: string | null;
}
