/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingApplicationApiDescriptionModelModules } from './voloAbpHttpModelingApplicationApiDescriptionModelModules';
import type { VoloAbpHttpModelingApplicationApiDescriptionModelTypes } from './voloAbpHttpModelingApplicationApiDescriptionModelTypes';

export interface VoloAbpHttpModelingApplicationApiDescriptionModel {
  modules?: VoloAbpHttpModelingApplicationApiDescriptionModelModules;
  types?: VoloAbpHttpModelingApplicationApiDescriptionModelTypes;
}
