/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentUserDto {
  email?: string | null;
  emailVerified?: boolean;
  id?: string | null;
  impersonatorTenantId?: string | null;
  impersonatorTenantName?: string | null;
  impersonatorUserId?: string | null;
  impersonatorUserName?: string | null;
  isAuthenticated?: boolean;
  name?: string | null;
  phoneNumber?: string | null;
  phoneNumberVerified?: boolean;
  roles?: string[] | null;
  surName?: string | null;
  tenantId?: string | null;
  userName?: string | null;
}
