/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionEnumDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionEnumDto';

export type VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoEnums = {[key: string]: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionEnumDto} | null;
