/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpIdentityIdentityUserDto } from './voloAbpIdentityIdentityUserDto';

export interface VoloAbpApplicationDtosPagedResultDto1VoloAbpIdentityIdentityUserDtoVoloAbpIdentityApplicationContractsVersion7020CultureNeutralPublicKeyTokenNull {
  items?: VoloAbpIdentityIdentityUserDto[] | null;
  totalCount?: number;
}
