/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { IIASAFieldSurveyDtosReviewDto } from './iIASAFieldSurveyDtosReviewDto';

export interface VoloAbpApplicationDtosPagedResultDto1IIASAFieldSurveyDtosReviewDtoIIASAFieldSurveyApplicationContractsVersion1000CultureNeutralPublicKeyTokenNull {
  items?: IIASAFieldSurveyDtosReviewDto[] | null;
  totalCount?: number;
}
