/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDtoConfiguration } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDtoConfiguration';
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDtoEntities } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDtoEntities';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDto {
  configuration?: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDtoConfiguration;
  entities?: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDtoEntities;
}
