/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpFeatureManagementFeatureProviderDto } from './voloAbpFeatureManagementFeatureProviderDto';
import type { VoloAbpValidationStringValuesIStringValueType } from './voloAbpValidationStringValuesIStringValueType';

export interface VoloAbpFeatureManagementFeatureDto {
  depth?: number;
  description?: string | null;
  displayName?: string | null;
  name?: string | null;
  parentName?: string | null;
  provider?: VoloAbpFeatureManagementFeatureProviderDto;
  value?: string | null;
  valueType?: VoloAbpValidationStringValuesIStringValueType;
}
