/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAccountRegisterDtoExtraProperties } from './voloAbpAccountRegisterDtoExtraProperties';

export interface VoloAbpAccountRegisterDto {
  appName: string;
  emailAddress: string;
  readonly extraProperties?: VoloAbpAccountRegisterDtoExtraProperties;
  password: string;
  userName: string;
}
