/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export type VoloAbpAccountWebAreasAccountControllersModelsLoginResultType = typeof VoloAbpAccountWebAreasAccountControllersModelsLoginResultType[keyof typeof VoloAbpAccountWebAreasAccountControllersModelsLoginResultType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoloAbpAccountWebAreasAccountControllersModelsLoginResultType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
} as const;
