/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpIdentityIdentityUserDtoExtraProperties } from './voloAbpIdentityIdentityUserDtoExtraProperties';

export interface VoloAbpIdentityIdentityUserDto {
  concurrencyStamp?: string | null;
  creationTime?: string;
  creatorId?: string | null;
  deleterId?: string | null;
  deletionTime?: string | null;
  email?: string | null;
  emailConfirmed?: boolean;
  readonly extraProperties?: VoloAbpIdentityIdentityUserDtoExtraProperties;
  id?: string;
  isActive?: boolean;
  isDeleted?: boolean;
  lastModificationTime?: string | null;
  lastModifierId?: string | null;
  lockoutEnabled?: boolean;
  lockoutEnd?: string | null;
  name?: string | null;
  phoneNumber?: string | null;
  phoneNumberConfirmed?: boolean;
  surname?: string | null;
  tenantId?: string | null;
  userName?: string | null;
}
