/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingMethodParameterApiDescriptionModelDefaultValue } from './voloAbpHttpModelingMethodParameterApiDescriptionModelDefaultValue';

export interface VoloAbpHttpModelingMethodParameterApiDescriptionModel {
  defaultValue?: VoloAbpHttpModelingMethodParameterApiDescriptionModelDefaultValue;
  isOptional?: boolean;
  name?: string | null;
  type?: string | null;
  typeAsString?: string | null;
  typeSimple?: string | null;
}
