/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpTenantManagementTenantDto } from './voloAbpTenantManagementTenantDto';

export interface VoloAbpApplicationDtosPagedResultDto1VoloAbpTenantManagementTenantDtoVoloAbpTenantManagementApplicationContractsVersion7020CultureNeutralPublicKeyTokenNull {
  items?: VoloAbpTenantManagementTenantDto[] | null;
  totalCount?: number;
}
