/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingTypeApiDescriptionModel } from './voloAbpHttpModelingTypeApiDescriptionModel';

export type VoloAbpHttpModelingApplicationApiDescriptionModelTypes = {[key: string]: VoloAbpHttpModelingTypeApiDescriptionModel} | null;
