/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingActionApiDescriptionModel } from './voloAbpHttpModelingActionApiDescriptionModel';

export type VoloAbpHttpModelingControllerApiDescriptionModelActions = {[key: string]: VoloAbpHttpModelingActionApiDescriptionModel} | null;
