/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoEnums } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoEnums';
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoModules } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoModules';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDto {
  enums?: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoEnums;
  modules?: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoModules;
}
