/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpValidationStringValuesIValueValidatorProperties } from './voloAbpValidationStringValuesIValueValidatorProperties';

export interface VoloAbpValidationStringValuesIValueValidator {
  readonly name?: string | null;
  readonly properties?: VoloAbpValidationStringValuesIValueValidatorProperties;
}
