/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAccountUpdateProfileDtoExtraProperties } from './voloAbpAccountUpdateProfileDtoExtraProperties';

export interface VoloAbpAccountUpdateProfileDto {
  concurrencyStamp?: string | null;
  email?: string | null;
  readonly extraProperties?: VoloAbpAccountUpdateProfileDtoExtraProperties;
  name?: string | null;
  phoneNumber?: string | null;
  surname?: string | null;
  userName?: string | null;
}
