/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsIanaTimeZone } from './voloAbpAspNetCoreMvcApplicationConfigurationsIanaTimeZone';
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone } from './voloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsTimeZone {
  iana?: VoloAbpAspNetCoreMvcApplicationConfigurationsIanaTimeZone;
  windows?: VoloAbpAspNetCoreMvcApplicationConfigurationsWindowsTimeZone;
}
