/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpRemoteServiceErrorInfoData } from './voloAbpHttpRemoteServiceErrorInfoData';
import type { VoloAbpHttpRemoteServiceValidationErrorInfo } from './voloAbpHttpRemoteServiceValidationErrorInfo';

export interface VoloAbpHttpRemoteServiceErrorInfo {
  code?: string | null;
  data?: VoloAbpHttpRemoteServiceErrorInfoData;
  details?: string | null;
  message?: string | null;
  validationErrors?: VoloAbpHttpRemoteServiceValidationErrorInfo[] | null;
}
