/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpFeatureManagementFeatureDto } from './voloAbpFeatureManagementFeatureDto';

export interface VoloAbpFeatureManagementFeatureGroupDto {
  displayName?: string | null;
  features?: VoloAbpFeatureManagementFeatureDto[] | null;
  name?: string | null;
}
