/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingInterfaceMethodApiDescriptionModel } from './voloAbpHttpModelingInterfaceMethodApiDescriptionModel';

export interface VoloAbpHttpModelingControllerInterfaceApiDescriptionModel {
  methods?: VoloAbpHttpModelingInterfaceMethodApiDescriptionModel[] | null;
  name?: string | null;
  type?: string | null;
}
