/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationSettingConfigurationDtoValues } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationSettingConfigurationDtoValues';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationSettingConfigurationDto {
  values?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationSettingConfigurationDtoValues;
}
