/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDtoResources } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDtoResources';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDto {
  resources?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDtoResources;
}
