/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export interface VoloAbpLocalizationLanguageInfo {
  cultureName?: string | null;
  displayName?: string | null;
  flagIcon?: string | null;
  readonly twoLetterISOLanguageName?: string | null;
  uiCultureName?: string | null;
}
