/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export interface VoloAbpSettingManagementUpdateEmailSettingsDto {
  defaultFromAddress: string;
  defaultFromDisplayName: string;
  smtpDomain?: string | null;
  smtpEnableSsl?: boolean;
  smtpHost?: string | null;
  smtpPassword?: string | null;
  smtpPort?: number;
  smtpUseDefaultCredentials?: boolean;
  smtpUserName?: string | null;
}
