/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export interface VoloAbpHttpModelingPropertyApiDescriptionModel {
  isRequired?: boolean;
  jsonName?: string | null;
  maximum?: string | null;
  maxLength?: number | null;
  minimum?: string | null;
  minLength?: number | null;
  name?: string | null;
  regex?: string | null;
  type?: string | null;
  typeSimple?: string | null;
}
