/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDtoTexts } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDtoTexts';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto {
  baseResources?: string[] | null;
  texts?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDtoTexts;
}
