/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto {
  calendarAlgorithmType?: string | null;
  dateSeparator?: string | null;
  dateTimeFormatLong?: string | null;
  fullDateTimePattern?: string | null;
  longTimePattern?: string | null;
  shortDatePattern?: string | null;
  shortTimePattern?: string | null;
}
