/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoConfiguration } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoConfiguration';
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoProperties } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoProperties';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto {
  configuration?: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoConfiguration;
  properties?: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoProperties;
}
