/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAccountProfileDtoExtraProperties } from './voloAbpAccountProfileDtoExtraProperties';

export interface VoloAbpAccountProfileDto {
  concurrencyStamp?: string | null;
  email?: string | null;
  readonly extraProperties?: VoloAbpAccountProfileDtoExtraProperties;
  hasPassword?: boolean;
  isExternal?: boolean;
  name?: string | null;
  phoneNumber?: string | null;
  surname?: string | null;
  userName?: string | null;
}
