/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementProviderInfoDto } from './voloAbpPermissionManagementProviderInfoDto';

export interface VoloAbpPermissionManagementPermissionGrantInfoDto {
  allowedProviders?: string[] | null;
  displayName?: string | null;
  grantedProviders?: VoloAbpPermissionManagementProviderInfoDto[] | null;
  isGranted?: boolean;
  name?: string | null;
  parentName?: string | null;
}
