/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAccountChangePasswordInput {
  currentPassword?: string | null;
  newPassword: string;
}
