/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingMethodParameterApiDescriptionModel } from './voloAbpHttpModelingMethodParameterApiDescriptionModel';
import type { VoloAbpHttpModelingReturnValueApiDescriptionModel } from './voloAbpHttpModelingReturnValueApiDescriptionModel';

export interface VoloAbpHttpModelingInterfaceMethodApiDescriptionModel {
  name?: string | null;
  parametersOnMethod?: VoloAbpHttpModelingMethodParameterApiDescriptionModel[] | null;
  returnValue?: VoloAbpHttpModelingReturnValueApiDescriptionModel;
}
