/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */

export type VoloAbpIdentityIdentityUserDtoExtraProperties = {[key: string]: {}} | null;
