/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { VoloAbpIdentityIdentityRoleDto } from './voloAbpIdentityIdentityRoleDto';

export interface VoloAbpApplicationDtosListResultDto1VoloAbpIdentityIdentityRoleDtoVoloAbpIdentityApplicationContractsVersion7020CultureNeutralPublicKeyTokenNull {
  items?: VoloAbpIdentityIdentityRoleDto[] | null;
}
