/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * FieldSurvey API
 * OpenAPI spec version: v1
 */
import type { IIASAFieldSurveyDtosSurveyDtoForGet } from './iIASAFieldSurveyDtosSurveyDtoForGet';

export interface VoloAbpApplicationDtosPagedResultDto1IIASAFieldSurveyDtosSurveyDtoForGetIIASAFieldSurveyApplicationContractsVersion1000CultureNeutralPublicKeyTokenNull {
  items?: IIASAFieldSurveyDtosSurveyDtoForGet[] | null;
  totalCount?: number;
}
